### ISSUE TITLE
Error in Part 7 of tictoc tutorial

### ISSUE THREAD

**Issue by Fanfoue** [omnetpp/tutorials#15]
Part 7 of tictoc tutorial creates a parametrized network with a given number of central nodes.
In the .ned file, there is an error in the connections.
It is currently written:
```
        for i=2..numCentralNodes+1 {
            tic[i].gate++ <--> Channel <--> tic[i+1].gate++;
        }
```
The for-loop should stop at numCentralNodes instead of numCentralNodes+1.
The connection created for i = num+1 is not part of the central path,
and is already created in the next lines:
```
        // connect the 2 nodes on the other side to the central nodes
        tic[numCentralNodes+2].gate++ <--> Channel <--> tic[numCentralNodes+1].gate++;
        tic[numCentralNodes+3].gate++ <--> Channel <--> tic[numCentralNodes+1].gate++;
```
With current code, the node tic[numCentralNodes+1] is connected twice with tic[numCentralNodes+2].
For example, see attached screenshot with numCentralNodes=2, node 3 is connected twice to node 4.
If you want me to make a PR or if you need more info, let me know.

![ScreenshotWithNum=2](https://user-images.githubusercontent.com/3082614/118437800-3883dd80-b71e-11eb-915d-ddd0851e8109.png)

**Comment by torokati44** [comment]
Oh, you are absolutely right. Nice catch, thank you! Sorry for the significant delay in response.
The mistake was probably made because in NED, for historical reasons, `for` loops are inclusive on the right end of the range, and here this was not taken into account.
