### ISSUE TITLE
somtihng wrong in tictic10

### ISSUE THREAD

**Issue by jianglongrong** [omnetpp/tutorials#18]

**Comment by jianglongrong** [comment]
In my comoputer(windows10), omnet++ version is 6.0.1, i check the tictic10.ned file, but it didn't show in the [official tutorial tictoc10's](https://docs.omnetpp.org/tutorials/tictoc/part4/) network topology!
here is the code in .ned file and picture:
```
// This file is part of an OMNeT++/OMNEST simulation example.
//
// Copyright (C) 2003-2015 Andras Varga
//
// This file is distributed WITHOUT ANY WARRANTY. See the file
// `license' for details on this and other legal matters.
//
simple Txc10
{
    parameters:
        @display("i=block/routing");
    gates:
        input in[];  // declare in[] and out[] to be vector gates
        output out[];
}

network Tictoc10
{
    @display("bgb=382,308");
    submodules:
        tic[6]: Txc10 {
            @display("p=95,103");
        }
    connections:
        tic[0].out++ --> {  delay = 100ms; } --> tic[1].in++;
        tic[0].in++ <-- {  delay = 100ms; } <-- tic[1].out++;

        tic[1].out++ --> {  delay = 100ms; } --> tic[2].in++;
        tic[1].in++ <-- {  delay = 100ms; } <-- tic[2].out++;

        tic[1].out++ --> {  delay = 100ms; } --> tic[4].in++;
        tic[1].in++ <-- {  delay = 100ms; } <-- tic[4].out++;

        tic[3].out++ --> {  delay = 100ms; } --> tic[4].in++;
        tic[3].in++ <-- {  delay = 100ms; } <-- tic[4].out++;

        tic[4].out++ --> {  delay = 100ms; } --> tic[5].in++;
        tic[4].in++ <-- {  delay = 100ms; } <-- tic[5].out++;
}
```
## in my omnet software the network topology is:

![屏幕截图 2023-05-26 180103](https://github.com/omnetpp/docs.omnetpp.org/assets/46858473/cb40ef8b-496f-4d93-a8be-93387ad9769b)

## in official  tutorial the network topology is:

![屏幕截图 2023-05-26 180250](https://github.com/omnetpp/docs.omnetpp.org/assets/46858473/122800f2-29ef-4fb1-9604-46966c625185)

## i click the re-layout, but it didn't work,  i get confused!  :(

**Comment by rhornig** [comment]
You specified an exact coordinate for the whole vector (`@display("p=95,103");`) so everything was placed to that position. Better delete the `@display` attribute and leave the layouting to the auto layouter. Note that whenever you drag the module vector in the IDE, it will again pin all modules to that position.
