### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by esfandia** [omnetpp/tutorials#7]
I have noticed a few broken links in the tutorials:

- the link in the tutorial header (for example at https://docs.omnetpp.org/ ) to the Github repo at https://github.com/omnetpp/omnetpp-docs returns a 404.

- many links to the tictoc source code are broken, as the period at the end of the sentence ends up included in the link. For example in  https://docs.omnetpp.org/tutorials/tictoc/part3/ look for "You can read Tic's full source in txc8.cc." Or in https://docs.omnetpp.org/tutorials/tictoc/part4/ look for "Read the full code: txc13.cc." I'm happy to fix these myself and post a PR, but I imagine the docs are auto-generated.

**Comment by avarga** [comment]
Thank you for reporting, we'll fix them.

**Comment by rhornig** [comment]
Fixed them. Thanks for the report.
