### ISSUE TITLE
Broken snippet include in TicToc tutorial

### ISSUE THREAD

**Issue by englishm** [omnetpp/tutorials#9]
I'm not sure why, but this include doesn't appear to be working in the Tic Toc tutorial launched from the OMNeT++ IDE in the Instant Veins (version 4.7.1-i1) virtual appliance:

https://github.com/omnetpp/docs.omnetpp.org/blob/786f29bc31668eb4ffd307d31427042d4d0363df/docs/tutorials/tictoc/part1.md#L67

It looks like this:

![VirtualBox_instant-veins-4 7 1-i1_06_04_2019_13_52_56](https://user-images.githubusercontent.com/1165411/55673245-5ca03f80-5873-11e9-87af-702bf9bb9af1.png)

*Edit:* the code itself is present, so I'm not sure why it isn't rendering:

https://github.com/omnetpp/docs.omnetpp.org/blob/786f29bc31668eb4ffd307d31427042d4d0363df/docs/tutorials/tictoc/code/tictoc1.ned#L12-L31

**Comment by rhornig** [comment]
The inclusion is done using javascript, so probably the internal eclipse browser has some problems with executing javascript. That would definitely prevent the inclusions properly appearing.
